- validation step to check if the tar file is a valid gzip archive - Ensure kernel_cmdline is defined before appending

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,7 +63,11 @@ jobs:
           wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage1.bin
           wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage2.bin
           cd /tmp
+          if file pppwn.tar.gz | grep -q 'gzip compressed data'; then
           tar -czf pppwn.tar.gz pppwnlive/*
+          else
+            echo "Error: Invalid gzip file" && exit 1
+          fi
 
       - name: Install required packages
         shell: alpine --root {0}
