I think I found the problem

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -33,7 +33,15 @@ jobs:
           cp ./custom/pppwn.tar.gz aports/scripts/
           chmod +x aports/scripts/*
           sh aports/scripts/mkimage.sh --tag edge --outdir ~/iso --arch x86_64 --repository https://dl-cdn.alpinelinux.org/alpine/edge/main --profile pppwn
-          
+
+      - name: Check if ISO was created (in Alpine)
+        shell: alpine.sh --root {0}
+        run: |
+          if [ -z "$(ls -A ~/iso/*.iso 2>/dev/null)" ]; then
+            echo "ISO not found. Exiting."
+            exit 1
+          fi
+
       - name: Check if ISO was created
         run: |
           if [ -z "$(ls -A ~/iso/*.iso 2>/dev/null)" ]; then
